# Generated by Django 3.0.8 on 2020-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cohesion', models.IntegerField(default=0)),
                ('Shear_Strength', models.IntegerField(default=0)),
                ('Length', models.IntegerField(default=0)),
                ('Depth', models.IntegerField(default=0)),
                ('Width', models.IntegerField(default=0)),
                ('Inclination', models.IntegerField(default=0)),
                ('Water_Unit_Weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Ground_Water_Depth', models.IntegerField(default=0)),
                ('Dry_Soil_Unit_Weight', models.IntegerField(default=0)),
                ('Saturated_Soil_Unit_Weight', models.IntegerField(default=0)),
                ('Unit_Weight_Below_Foundation', models.IntegerField(default=0)),
                ('Factor_of_Safety', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='capacity_rock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UCS', models.IntegerField(default=0)),
                ('Shear_Strength', models.IntegerField(default=0)),
                ('Factor_of_Safety', models.IntegerField(default=5)),
            ],
        ),
    ]


